export const GET_SEARCH_RESULTS_START = 'GET_SEARCH_RESULTS_START';
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS';
export const GET_SEARCH_RESULTS_FAIL = 'GET_SEARCH_RESULTS_FAIL';

export const GET_SUGGESTIONS_START = 'GET_SUGGESTIONS_START';
export const GET_SUGGESTIONS_SUCCESS = 'GET_SUGGESTIONS_SUCCESS';
export const GET_SUGGESTIONS_FAIL = 'GET_SUGGESTIONS_FAIL';

export const SORT_SEARCH_RESULTS = 'SORT_SEARCH_RESULTS';
export const RESET_SUGGESTIONS = 'RESET_SUGGESTIONS';
